image: php
labels:
  - role=php
working_dir: /src
network_mode: host
restart: unless-stopped
cap_drop:
  - ALL
cap_add:
  - CHOWN
volumes:
  - env-storage:/src/env:rw
environment:
  - PROJECT=$COMPOSE_PROJECT_NAME
  - PROJECT_ENV=$PROJECT_ENV
